services:
  mysql-e2e:
    image: 'mysql:latest'
    container_name: 'back_mysql_e2e'
    environment:
      - 'MYSQL_DATABASE=test_e2e'
      - 'MYSQL_USER=user_test'
      - 'MYSQL_PASSWORD=test_password'
      - 'MYSQL_ROOT_PASSWORD=root_password'
    ports:
      - '3307:3306'
    volumes:
      - db_e2e_data:/var/lib/mysql
volumes:
  db_e2e_data: